export const styles = {
  container: {
    maxWidth: "480px",
    margin: "0 auto",
    backgroundColor: "#FFFFFF",
    minHeight: "100vh",
    fontFamily: '"Epilogue", system-ui, -apple-system, sans-serif',
    color: "#000000",
    boxShadow: "0 0 20px rgba(0,0,0,0.05)",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 50,
    backgroundColor: "#FFFFFF",
    borderBottom: "2px solid #000000",
    padding: "12px 16px",
  },
  navRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  iconBtn: {
    background: "none",
    border: "none",
    cursor: "pointer",
    color: "#000000",
  },
  brandTitle: {
    display: "flex",
    alignItems: "center",
    fontWeight: "800",
    fontSize: "1.1rem",
    letterSpacing: "1px",
    color: "#000000",
  },
  brandIcon: {
    marginRight: "6px",
    color: "#009379",
  },
  cartContainer: {
    position: "relative",
    cursor: "pointer",
  },
  badge: {
    position: "absolute",
    top: "-6px",
    right: "-8px",
    backgroundColor: "#009379",
    color: "#FFFFFF",
    fontSize: "0.7rem",
    fontWeight: "bold",
    borderRadius: "50%",
    width: "18px",
    height: "18px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "1px solid #000000",
  },
  mobileNav: {
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    marginTop: "12px",
    paddingTop: "12px",
    borderTop: "2px solid #000000",
  },
  navLink: {
    textDecoration: "none",
    color: "#000000",
    fontWeight: "700",
    fontSize: "0.95rem",
  },
  main: {
    paddingBottom: "24px",
  },
  hero: {
    backgroundColor: "#F9E6F0",
    borderBottom: "2px solid #000000",
    padding: "24px 16px",
    position: "relative",
  },
  heroOverlay: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    color: "#000000",
  },
  heroTag: {
    color: "#009379",
    fontSize: "0.75rem",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
  },
  heroTitle: {
    fontSize: "1.5rem",
    margin: "8px 0",
    lineHeight: "1.2",
    fontWeight: "800",
  },
  heroSubtitle: {
    fontSize: "0.85rem",
    color: "#000000",
    marginBottom: "16px",
    lineHeight: "1.4",
  },
  primaryBtn: {
    backgroundColor: "#009379",
    color: "#FFFFFF",
    border: "2px solid #000000",
    borderRadius: "8px",
    padding: "10px 18px",
    fontWeight: "700",
    fontSize: "0.85rem",
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    boxShadow: "2px 2px 0px #000000",
  },
  infoBar: {
    display: "flex",
    justifyContent: "space-around",
    backgroundColor: "#FFFFFF",
    padding: "12px",
    borderBottom: "2px solid #000000",
  },
  infoItem: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  infoIcon: {
    color: "#009379",
    fontSize: "1.1rem",
  },
  infoTextTop: {
    display: "block",
    fontSize: "0.75rem",
    color: "#000000",
    fontWeight: "700",
  },
  infoTextSub: {
    display: "block",
    fontSize: "0.7rem",
    color: "#000000",
  },
  section: {
    padding: "20px 16px",
  },
  sectionTitle: {
    fontSize: "1.3rem",
    fontWeight: "800",
    marginBottom: "14px",
  },
  tabsContainer: {
    display: "flex",
    gap: "8px",
    overflowX: "auto",
    paddingBottom: "8px",
    marginBottom: "16px",
  },
  tabBtn: {
    backgroundColor: "#FFFFFF",
    border: "2px solid #000000",
    borderRadius: "8px",
    padding: "6px 14px",
    fontSize: "0.8rem",
    fontWeight: "700",
    color: "#000000",
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  activeTabBtn: {
    backgroundColor: "#F9E6F0",
    color: "#000000",
    borderColor: "#000000",
  },
  loadingContainer: {
    padding: "40px 0",
    textAlign: "center",
    color: "#000000",
    fontSize: "0.9rem",
    fontWeight: "600",
  },
  menuGrid: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  card: {
    backgroundColor: "#FFFFFF",
    borderRadius: "12px",
    border: "2px solid #000000",
    overflow: "hidden",
    boxShadow: "3px 3px 0px #000000",
    display: "flex",
    flexDirection: "column",
  },
  cardImageContainer: {
    position: "relative",
    height: "150px",
    borderBottom: "2px solid #000000",
  },
  cardImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  favBtn: {
    position: "absolute",
    top: "10px",
    right: "10px",
    backgroundColor: "#FFFFFF",
    border: "2px solid #000000",
    borderRadius: "50%",
    width: "34px",
    height: "34px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
  },
  popularBadge: {
    position: "absolute",
    bottom: "10px",
    left: "10px",
    backgroundColor: "#009379",
    color: "#FFFFFF",
    fontSize: "0.65rem",
    fontWeight: "700",
    padding: "2px 8px",
    borderRadius: "6px",
    border: "1px solid #000000",
  },
  cardContent: {
    padding: "14px",
  },
  cardHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardTitle: {
    fontSize: "1rem",
    fontWeight: "800",
    margin: 0,
  },
  rating: {
    display: "flex",
    alignItems: "center",
    gap: "4px",
  },
  ratingValue: {
    fontSize: "0.75rem",
    fontWeight: "700",
  },
  cardDescription: {
    fontSize: "0.75rem",
    color: "#000000",
    margin: "8px 0",
    lineHeight: "1.4",
  },
  cardFooter: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: "12px",
  },
  price: {
    fontSize: "1rem",
    fontWeight: "800",
    color: "#009379",
  },
  addCartBtn: {
    backgroundColor: "#F9E6F0",
    color: "#000000",
    border: "2px solid #000000",
    borderRadius: "6px",
    padding: "6px 12px",
    fontSize: "0.75rem",
    fontWeight: "700",
    cursor: "pointer",
  },
  coffeeSection: {
    backgroundColor: "#F9E6F0",
    margin: "0 16px",
    padding: "20px",
    borderRadius: "12px",
    border: "2px solid #000000",
    boxShadow: "3px 3px 0px #000000",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  coffeeTitle: {
    fontSize: "1.1rem",
    fontWeight: "800",
    color: "#000000",
    margin: "8px 0 4px 0",
  },
  coffeeDesc: {
    fontSize: "0.75rem",
    color: "#000000",
    lineHeight: "1.4",
    margin: 0,
  },
  footer: {
    backgroundColor: "#FFFFFF",
    color: "#000000",
    padding: "24px 16px",
    fontSize: "0.8rem",
    borderTop: "2px solid #000000",
    marginTop: "24px",
  },
  footerTitle: {
    color: "#000000",
    fontSize: "1rem",
    fontWeight: "800",
    marginBottom: "12px",
  },
  footerText: {
    margin: "6px 0",
    display: "flex",
    alignItems: "center",
  },
  copyright: {
    marginTop: "16px",
    paddingTop: "12px",
    borderTop: "1px solid #000000",
    fontSize: "0.7rem",
    textAlign: "center",
  },
};
